web:
    build: .
    links:
        - mysql
    expose:
        - 80
    volumes:
        - .:/app
mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    expose:
        - 3306
